name: access-test
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  workflow_dispatch:
    inputs:
      namespace:
        type: string

jobs:
  install-test:
    permissions:
      scm-token-own: read
      id-token: write
    steps:
    - name: Login to AWS
      uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ vars.oidc_staging_iam_role }}
        role-duration-seconds: "3600"
    - uses: cloudbees-io/configure-eks-credentials@v1
      with:
        name: ${{ vars.staging_east_cluster_name }}
    - id: createns
      name: Create Kubernetes Namespace
      uses: cloudbees-io/create-k8s-namespace@v1
      with:
        name: ${{ inputs.namespace }}
        sanitize-name: false
        labels: |
          cloudbees.io/cleanup: "true"
    - name: List namespaces
      uses: docker://alpine/k8s:1.31.2
      run: |
        set -ux
        kubectl get ns
    - name: Delete namespaces
      uses: docker://alpine/k8s:1.31.2
      run: |
        set -ux
        kubectl delete ns ${{ inputs.namespace }}